### ISSUE TITLE
I can get UB via only safe code

### ISSUE THREAD

**Issue by schulace** [yihuang/non-empty-vec#5]
```rust
let mut v = NonEmpty::new(vec![1]).unwrap();
AsMut::<Vec<i32>>::as_mut(&mut v).pop();
AsMut::<Vec<i32>>::as_mut(&mut v).shrink_to_fit();
println!("{}", v.first());
```

This produces a segfault. You should probably remove the `AsMut<Vec<T>>` implementation

**Comment by yihuang** [comment]
https://github.com/yihuang/non-empty-vec/pull/8
Do you think it's safe to do `AsMut<[T]>`?

**Comment by schulace** [comment]
Yeah that should be fine. The issue here was that giving direct access to the Vec lets a user pop the first element, and your `first` function does an unchecked access. Since `&mut [T]` doesn't provide a way to change the size of the vector you're OK to implement it
